apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  labels:
    app: hm-medlemskap
    team: teamdigihot
  name: hm-medlemskap
  namespace: teamdigihot
spec:
  image: "{{image}}"
  strategy:
    type: Recreate
  startup:
    failureThreshold: 5
    initialDelay: 45
    path: /isalive
  liveness:
    path: /isalive
  readiness:
    path: /isready
  port: 8080
  prometheus:
    enabled: true
    path: /metrics
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
  replicas:
    max: 1
    min: 1
  azure:
    application:
      enabled: true
  kafka:
    pool: nav-dev
  resources:
    limits:
      cpu: 250m
      memory: 1024Mi
    requests:
      cpu: 100m
      memory: 512Mi
  secureLogs:
    enabled: true
  accessPolicy:
    outbound:
      rules:
        - application: hm-saksbehandling
      external:
        - host: login.microsoftonline.com
  env:
  {{#each this}}
     - name: {{@key}}
       value: "{{this}}"
  {{/each}}
